name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  distcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcmocka-dev libcmocka0
      - name: Copy missing files
        run: autoreconf --install
      - name: Configure
        run: ./configure
      - name: Check distribution
        run: make distcheck
