name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gawk
      - name: Copy missing files
        run: autoreconf --install
      - name: Configure
        run: ./configure --disable-tests
      - name: Generate distribution
        run: make dist
      - name: Generate release notes
        run: build-aux/release-notes.sh >${{ github.workspace }}-RELEASE.md
      - uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-RELEASE.md
          files: libi2cd-*.tar.gz
