name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gawk
      - name: Copy missing files
        run: autoreconf --install
      - name: Configure
        run: ./configure --disable-tests
      - name: Generate distribution
        run: make dist
      - name: Generate release notes
        run: |
          echo 'RELEASE_BODY<<' >>$GITHUB_ENV
          build-aux/release-notes.sh ${GITHUB_REF##*/} >>$GITHUB_ENV
          echo 'EOF' >>$GITHUB_ENV
      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ env.RELEASE_BODY }}
          files: libi2cd-*.tar.gz
